# Model settings
val_every: 2
model_checkpoint_interval: 1
seed: 0
model:
  name: LaneATT
  parameters:
    backbone: resnet18
    S: &S 72
    topk_anchors: 1000
    #anchors_freq_path: 'data/tusimple_anchors_freq.pt'
    anchors_freq_path: 'data/tusimple_250418pm_anchors_mask.pt'
    #anchors_freq_path: 'data/tusimple_250423_anchors_mask.pt'
    img_h: &img_h 360
    img_w: &img_w 640
batch_size: 8
epochs: 40
loss_parameters: {}
train_parameters:
  conf_threshold:
  nms_thres: 15.
  nms_topk: 3000
test_parameters:
  conf_threshold: 0.5
  nms_thres: 50.
  nms_topk: &max_lanes 4
optimizer:
  name: Adam
  parameters:
    lr: 0.0003
lr_scheduler:
  name: CosineAnnealingLR
  parameters:
    #T_max: 45400 # 100epochs * 454 iterations
    #T_max: 18500 # 20 * 925 iterations
    #T_max: 37000 # 40 * 925 iterations
    #T_max: 98080 # 20 * 4904 iterations
    #T_max: 216280 #20 * 10814 iterations
    T_max: 432560  # 40 * 10814， 20250425PM1
    #T_max: 865120  # 80 * 10814, 20250426AM1
# Dataset settings
datasets:
  train: &train
    type: LaneDataset
    parameters:
      S: *S
      dataset: tusimple
      split: train
      img_size: [*img_h, *img_w]
      max_lanes: *max_lanes
      normalize: false
      aug_chance: 1.0
      augmentations:
        - name: Affine
          parameters:
            translate_px:
              x: !!python/tuple [-25, 25]
              y: !!python/tuple [-10, 10]
            rotate: !!python/tuple [-6, 6]
            scale: !!python/tuple [0.85, 1.15]
        - name: HorizontalFlip
          parameters:
            p: 0.5

      root: "datasets/TUSimple/tusimple"

  test:
    type: LaneDataset
    parameters:
      S: *S
      dataset: tusimple
      split: test
      img_size: [*img_h, *img_w]
      max_lanes: *max_lanes
      normalize: false
      aug_chance: 0
      augmentations:
      #root: "datasets/TUSimple/tusimple-test"
      root: "datasets/tusimple-0325"

  val:
    type: LaneDataset
    parameters:
      S: *S
      dataset: tusimple
      split: val
      img_size: [*img_h, *img_w]
      max_lanes: *max_lanes
      normalize: false
      aug_chance: 0
      augmentations:
      root: "datasets/TUSimple/tusimple"
      #root: "datasets/sampled_tusimple"